server:
  name: instance1.domain.com
  port: 8081
  public_url: https://instances.domain.com
  log:
    path: /home/eventnative/data/logs/
  metrics.prometheus.enabled: true

geo.maxmind_path: /home/eventnative/data/config

log:
  path: /home/eventnative/data/logs/events
  rotation_min: 5

sql_debug_log:
  ddl:
  queries:

api_keys:
  - id: my_website_key
    client_secret: '193b6281-f211-47a9-b384-102cf4cd2d55'
    server_secret: 'a6880b16-73d0-476e-840a-804b74f7684d'

destinations:
  redshift:
  bigquery:

sources:
  facebook:
  google_analytics:

users_recognition:
  enabled: true

coordination:
  type: redis

notifications:
  slack:
    url: https://slack_web_hook_url

ui:
  base_url: https://your_configurator_ui_host:5555

meta:
  storage:
    redis:
      host: redis_host
      port: 6379
      password: secret_password
      database: 0

node:
  pool_size: 1 # default
  max_space: 100 # default


 #"Source": "/home/jitsu/eventnative.yaml",
 #"Destination": "/home/eventnative/data/config/eventnative.yaml",

  #  corebos_jitsu_destination:
  #    type: npm
  #    package: corebos-jitsu-destination@1.0.0
  #    mode: stream
  #    config:
  #       url: "https://demo.corebos.com"
  #       event_types: "registration,error,comment"
  #       username: "admin"
  #       access_key: "cdYTBpiMR9RfGgO"
  #       instance_name: "demo-corebos"
  #       faq_id: "3x4681"
  #       comment: "${event_type}: From Axelera test net"
