import {ExtensionDescriptor} from "@jitsu/types/extension";
import {destination, validator, DestinationConfig} from "./destination";

const descriptor: ExtensionDescriptor = {
  id: "corebos-jitsu-destination",
  displayName: "corebos-jitsu-destination",
  icon: "",
  description: "Jitsu destination - corebos-jitsu-destination (generated by 'jitsu-cli extension create')",
  configurationParameters: [
    {id: "exampleParam", type: "string", required: true, displayName: "Example param", documentation: "Documentation"}
  ],
};

export { descriptor, destination, validator };